spring.application.name=greencycle
spring.ai.ollama.base-url=http://localhost:11434
ollama.model=gemma4:e4b
spring.security.user.name=admin
spring.security.user.password=admin
spring.datasource.url=jdbc:h2:file:./data/greencycle-db;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
